builds:
  - goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    hooks:
      pre: go generate
    flags:
      - tags=

archives:
  - id: binary
    format: binary

release:
  draft: true
  prerelease: true
