language: go

go:
  - 1.13.x

gobuild_args: -tags=dev

script:
  - go generate
  - go test -v ./...

# calls goreleaser
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL http://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
