# Packages required by generator
required = ["github.com/jteeuwen/go-bindata"]

[[constraint]]
  name = "github.com/golang/protobuf"
  branch = "master"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.2"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.2"

[[constraint]]
  name = "golang.org/x/net"
  branch = "master"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.10.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "v1.0.4"

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "v1.0.0"

[[constraint]]
  name = "github.com/buger/goterm"
  branch = "master"

[[constraint]]
  name = "github.com/coreos/go-oidc"
  branch = "master"

[[constraint]]
  name = "github.com/jteeuwen/go-bindata"
  branch = "master"
