# Packages required by generator
required = ["github.com/jteeuwen/go-bindata"]

[[constraint]]
  branch = "master"
  name = "github.com/buger/goterm"

[[constraint]]
  name = "github.com/coreos/go-oidc"
  version = "2.0.0"

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[[constraint]]
  name = "github.com/golang/protobuf"
  branch = "master"
  #version = "1.2.0"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  version = "1.0.0"

[[constraint]]
  name = "github.com/nlnwa/veidemann-api-go"
  version = "=1.0.0-beta3"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.2.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  branch = "master"
  #version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.3.1"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.17.0"

[prune]
  go-tests = true
  unused-packages = true
