// Code generated by protoc-gen-go. DO NOT EDIT.
// source: frontier.proto

package veidemann_api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CrawlSeedRequest struct {
	Job  *CrawlJob `protobuf:"bytes,5,opt,name=job" json:"job,omitempty"`
	Seed *Seed     `protobuf:"bytes,6,opt,name=seed" json:"seed,omitempty"`
}

func (m *CrawlSeedRequest) Reset()                    { *m = CrawlSeedRequest{} }
func (m *CrawlSeedRequest) String() string            { return proto.CompactTextString(m) }
func (*CrawlSeedRequest) ProtoMessage()               {}
func (*CrawlSeedRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *CrawlSeedRequest) GetJob() *CrawlJob {
	if m != nil {
		return m.Job
	}
	return nil
}

func (m *CrawlSeedRequest) GetSeed() *Seed {
	if m != nil {
		return m.Seed
	}
	return nil
}

func init() {
	proto.RegisterType((*CrawlSeedRequest)(nil), "veidemann.api.CrawlSeedRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Frontier service

type FrontierClient interface {
	CrawlSeed(ctx context.Context, in *CrawlSeedRequest, opts ...grpc.CallOption) (*CrawlExecutionStatus, error)
}

type frontierClient struct {
	cc *grpc.ClientConn
}

func NewFrontierClient(cc *grpc.ClientConn) FrontierClient {
	return &frontierClient{cc}
}

func (c *frontierClient) CrawlSeed(ctx context.Context, in *CrawlSeedRequest, opts ...grpc.CallOption) (*CrawlExecutionStatus, error) {
	out := new(CrawlExecutionStatus)
	err := grpc.Invoke(ctx, "/veidemann.api.Frontier/CrawlSeed", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Frontier service

type FrontierServer interface {
	CrawlSeed(context.Context, *CrawlSeedRequest) (*CrawlExecutionStatus, error)
}

func RegisterFrontierServer(s *grpc.Server, srv FrontierServer) {
	s.RegisterService(&_Frontier_serviceDesc, srv)
}

func _Frontier_CrawlSeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrawlSeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontierServer).CrawlSeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/veidemann.api.Frontier/CrawlSeed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontierServer).CrawlSeed(ctx, req.(*CrawlSeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Frontier_serviceDesc = grpc.ServiceDesc{
	ServiceName: "veidemann.api.Frontier",
	HandlerType: (*FrontierServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CrawlSeed",
			Handler:    _Frontier_CrawlSeed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "frontier.proto",
}

func init() { proto.RegisterFile("frontier.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xbf, 0x4f, 0x87, 0x30,
	0x10, 0xc5, 0x35, 0xea, 0x37, 0x5a, 0x85, 0x98, 0x3a, 0x40, 0x58, 0x34, 0x38, 0xa8, 0x4b, 0x07,
	0x1c, 0xdc, 0x31, 0x3a, 0x38, 0x19, 0xd8, 0x5c, 0x48, 0x0b, 0x07, 0xa9, 0x91, 0x3b, 0x6c, 0x8b,
	0xfa, 0xe7, 0x1b, 0x8a, 0xbf, 0x30, 0x8c, 0x97, 0xfb, 0xdc, 0x7b, 0xef, 0x1e, 0x0b, 0x5b, 0x43,
	0xe8, 0x34, 0x18, 0x31, 0x18, 0x72, 0xc4, 0x83, 0x37, 0xd0, 0x0d, 0xf4, 0x12, 0x51, 0xc8, 0x41,
	0x27, 0x47, 0x35, 0x61, 0xab, 0xbb, 0x79, 0x99, 0x84, 0x3d, 0x58, 0x2b, 0x3b, 0xb0, 0xf3, 0x9c,
	0xb6, 0xec, 0xf8, 0xd6, 0xc8, 0xf7, 0x97, 0x12, 0xa0, 0x29, 0xe0, 0x75, 0x04, 0xeb, 0xf8, 0x15,
	0xdb, 0x79, 0x26, 0x15, 0xef, 0x9d, 0x6d, 0x5f, 0x1e, 0x66, 0x91, 0x58, 0xc8, 0x09, 0x4f, 0x3f,
	0x90, 0x2a, 0x26, 0x86, 0x5f, 0xb0, 0x5d, 0x0b, 0xd0, 0xc4, 0x1b, 0xcf, 0x9e, 0xfc, 0x63, 0xbd,
	0xa8, 0x07, 0xb2, 0x8a, 0xed, 0xdf, 0x7f, 0xc5, 0xe4, 0x25, 0x3b, 0xf8, 0xf1, 0xe4, 0xa7, 0x6b,
	0xfa, 0x7f, 0xd2, 0x24, 0xe7, 0x6b, 0xc0, 0xdd, 0x07, 0xd4, 0xa3, 0xd3, 0x84, 0xa5, 0x93, 0x6e,
	0xb4, 0xe9, 0x56, 0x7e, 0xc3, 0x22, 0x24, 0x81, 0x4a, 0x20, 0xca, 0xe5, 0x45, 0x1e, 0x7c, 0x3b,
	0x3f, 0x4e, 0x2f, 0x3f, 0xfd, 0xf6, 0x53, 0xc9, 0x41, 0xab, 0x8d, 0x2f, 0xe2, 0xfa, 0x33, 0x00,
	0x00, 0xff, 0xff, 0xe6, 0x59, 0x76, 0x0c, 0x47, 0x01, 0x00, 0x00,
}
