// Code generated by protoc-gen-go. DO NOT EDIT.
// source: report.proto

package veidemann_api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Filter_Operator int32

const (
	Filter_EQ    Filter_Operator = 0
	Filter_NE    Filter_Operator = 1
	Filter_MATCH Filter_Operator = 2
	Filter_LT    Filter_Operator = 3
	Filter_GT    Filter_Operator = 4
)

var Filter_Operator_name = map[int32]string{
	0: "EQ",
	1: "NE",
	2: "MATCH",
	3: "LT",
	4: "GT",
}
var Filter_Operator_value = map[string]int32{
	"EQ":    0,
	"NE":    1,
	"MATCH": 2,
	"LT":    3,
	"GT":    4,
}

func (x Filter_Operator) String() string {
	return proto.EnumName(Filter_Operator_name, int32(x))
}
func (Filter_Operator) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_report_815df019fd9313b3, []int{0, 0}
}

type Filter struct {
	FieldName            string          `protobuf:"bytes,1,opt,name=field_name,json=fieldName" json:"field_name,omitempty"`
	Op                   Filter_Operator `protobuf:"varint,2,opt,name=op,enum=veidemann.api.Filter_Operator" json:"op,omitempty"`
	Value                string          `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Filter) Reset()         { *m = Filter{} }
func (m *Filter) String() string { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()    {}
func (*Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_report_815df019fd9313b3, []int{0}
}
func (m *Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filter.Unmarshal(m, b)
}
func (m *Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filter.Marshal(b, m, deterministic)
}
func (dst *Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filter.Merge(dst, src)
}
func (m *Filter) XXX_Size() int {
	return xxx_messageInfo_Filter.Size(m)
}
func (m *Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_Filter proto.InternalMessageInfo

func (m *Filter) GetFieldName() string {
	if m != nil {
		return m.FieldName
	}
	return ""
}

func (m *Filter) GetOp() Filter_Operator {
	if m != nil {
		return m.Op
	}
	return Filter_EQ
}

func (m *Filter) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type CrawlLogListRequest struct {
	WarcId               []string  `protobuf:"bytes,1,rep,name=warc_id,json=warcId" json:"warc_id,omitempty"`
	ExecutionId          string    `protobuf:"bytes,2,opt,name=execution_id,json=executionId" json:"execution_id,omitempty"`
	Filter               []*Filter `protobuf:"bytes,3,rep,name=filter" json:"filter,omitempty"`
	PageSize             int32     `protobuf:"varint,14,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
	Page                 int32     `protobuf:"varint,15,opt,name=page" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CrawlLogListRequest) Reset()         { *m = CrawlLogListRequest{} }
func (m *CrawlLogListRequest) String() string { return proto.CompactTextString(m) }
func (*CrawlLogListRequest) ProtoMessage()    {}
func (*CrawlLogListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_report_815df019fd9313b3, []int{1}
}
func (m *CrawlLogListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrawlLogListRequest.Unmarshal(m, b)
}
func (m *CrawlLogListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrawlLogListRequest.Marshal(b, m, deterministic)
}
func (dst *CrawlLogListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrawlLogListRequest.Merge(dst, src)
}
func (m *CrawlLogListRequest) XXX_Size() int {
	return xxx_messageInfo_CrawlLogListRequest.Size(m)
}
func (m *CrawlLogListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CrawlLogListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CrawlLogListRequest proto.InternalMessageInfo

func (m *CrawlLogListRequest) GetWarcId() []string {
	if m != nil {
		return m.WarcId
	}
	return nil
}

func (m *CrawlLogListRequest) GetExecutionId() string {
	if m != nil {
		return m.ExecutionId
	}
	return ""
}

func (m *CrawlLogListRequest) GetFilter() []*Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *CrawlLogListRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *CrawlLogListRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type CrawlLogListReply struct {
	Value                []*CrawlLog `protobuf:"bytes,1,rep,name=value" json:"value,omitempty"`
	Count                int64       `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
	PageSize             int32       `protobuf:"varint,14,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
	Page                 int32       `protobuf:"varint,15,opt,name=page" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CrawlLogListReply) Reset()         { *m = CrawlLogListReply{} }
func (m *CrawlLogListReply) String() string { return proto.CompactTextString(m) }
func (*CrawlLogListReply) ProtoMessage()    {}
func (*CrawlLogListReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_report_815df019fd9313b3, []int{2}
}
func (m *CrawlLogListReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrawlLogListReply.Unmarshal(m, b)
}
func (m *CrawlLogListReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrawlLogListReply.Marshal(b, m, deterministic)
}
func (dst *CrawlLogListReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrawlLogListReply.Merge(dst, src)
}
func (m *CrawlLogListReply) XXX_Size() int {
	return xxx_messageInfo_CrawlLogListReply.Size(m)
}
func (m *CrawlLogListReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CrawlLogListReply.DiscardUnknown(m)
}

var xxx_messageInfo_CrawlLogListReply proto.InternalMessageInfo

func (m *CrawlLogListReply) GetValue() []*CrawlLog {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *CrawlLogListReply) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *CrawlLogListReply) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *CrawlLogListReply) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type PageLogListRequest struct {
	WarcId               []string  `protobuf:"bytes,1,rep,name=warc_id,json=warcId" json:"warc_id,omitempty"`
	ExecutionId          string    `protobuf:"bytes,2,opt,name=execution_id,json=executionId" json:"execution_id,omitempty"`
	Filter               []*Filter `protobuf:"bytes,3,rep,name=filter" json:"filter,omitempty"`
	PageSize             int32     `protobuf:"varint,14,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
	Page                 int32     `protobuf:"varint,15,opt,name=page" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PageLogListRequest) Reset()         { *m = PageLogListRequest{} }
func (m *PageLogListRequest) String() string { return proto.CompactTextString(m) }
func (*PageLogListRequest) ProtoMessage()    {}
func (*PageLogListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_report_815df019fd9313b3, []int{3}
}
func (m *PageLogListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageLogListRequest.Unmarshal(m, b)
}
func (m *PageLogListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageLogListRequest.Marshal(b, m, deterministic)
}
func (dst *PageLogListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageLogListRequest.Merge(dst, src)
}
func (m *PageLogListRequest) XXX_Size() int {
	return xxx_messageInfo_PageLogListRequest.Size(m)
}
func (m *PageLogListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PageLogListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PageLogListRequest proto.InternalMessageInfo

func (m *PageLogListRequest) GetWarcId() []string {
	if m != nil {
		return m.WarcId
	}
	return nil
}

func (m *PageLogListRequest) GetExecutionId() string {
	if m != nil {
		return m.ExecutionId
	}
	return ""
}

func (m *PageLogListRequest) GetFilter() []*Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *PageLogListRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *PageLogListRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type PageLogListReply struct {
	Value                []*PageLog `protobuf:"bytes,1,rep,name=value" json:"value,omitempty"`
	Count                int64      `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
	PageSize             int32      `protobuf:"varint,14,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
	Page                 int32      `protobuf:"varint,15,opt,name=page" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PageLogListReply) Reset()         { *m = PageLogListReply{} }
func (m *PageLogListReply) String() string { return proto.CompactTextString(m) }
func (*PageLogListReply) ProtoMessage()    {}
func (*PageLogListReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_report_815df019fd9313b3, []int{4}
}
func (m *PageLogListReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageLogListReply.Unmarshal(m, b)
}
func (m *PageLogListReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageLogListReply.Marshal(b, m, deterministic)
}
func (dst *PageLogListReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageLogListReply.Merge(dst, src)
}
func (m *PageLogListReply) XXX_Size() int {
	return xxx_messageInfo_PageLogListReply.Size(m)
}
func (m *PageLogListReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PageLogListReply.DiscardUnknown(m)
}

var xxx_messageInfo_PageLogListReply proto.InternalMessageInfo

func (m *PageLogListReply) GetValue() []*PageLog {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *PageLogListReply) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *PageLogListReply) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *PageLogListReply) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type ScreenshotListRequest struct {
	Id                   []string  `protobuf:"bytes,1,rep,name=id" json:"id,omitempty"`
	ExecutionId          string    `protobuf:"bytes,2,opt,name=execution_id,json=executionId" json:"execution_id,omitempty"`
	Filter               []*Filter `protobuf:"bytes,3,rep,name=filter" json:"filter,omitempty"`
	ImgData              bool      `protobuf:"varint,4,opt,name=img_data,json=imgData" json:"img_data,omitempty"`
	PageSize             int32     `protobuf:"varint,14,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
	Page                 int32     `protobuf:"varint,15,opt,name=page" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ScreenshotListRequest) Reset()         { *m = ScreenshotListRequest{} }
func (m *ScreenshotListRequest) String() string { return proto.CompactTextString(m) }
func (*ScreenshotListRequest) ProtoMessage()    {}
func (*ScreenshotListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_report_815df019fd9313b3, []int{5}
}
func (m *ScreenshotListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScreenshotListRequest.Unmarshal(m, b)
}
func (m *ScreenshotListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScreenshotListRequest.Marshal(b, m, deterministic)
}
func (dst *ScreenshotListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScreenshotListRequest.Merge(dst, src)
}
func (m *ScreenshotListRequest) XXX_Size() int {
	return xxx_messageInfo_ScreenshotListRequest.Size(m)
}
func (m *ScreenshotListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ScreenshotListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ScreenshotListRequest proto.InternalMessageInfo

func (m *ScreenshotListRequest) GetId() []string {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ScreenshotListRequest) GetExecutionId() string {
	if m != nil {
		return m.ExecutionId
	}
	return ""
}

func (m *ScreenshotListRequest) GetFilter() []*Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *ScreenshotListRequest) GetImgData() bool {
	if m != nil {
		return m.ImgData
	}
	return false
}

func (m *ScreenshotListRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ScreenshotListRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type ScreenshotListReply struct {
	Value                []*Screenshot `protobuf:"bytes,1,rep,name=value" json:"value,omitempty"`
	Count                int64         `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
	PageSize             int32         `protobuf:"varint,14,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
	Page                 int32         `protobuf:"varint,15,opt,name=page" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ScreenshotListReply) Reset()         { *m = ScreenshotListReply{} }
func (m *ScreenshotListReply) String() string { return proto.CompactTextString(m) }
func (*ScreenshotListReply) ProtoMessage()    {}
func (*ScreenshotListReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_report_815df019fd9313b3, []int{6}
}
func (m *ScreenshotListReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScreenshotListReply.Unmarshal(m, b)
}
func (m *ScreenshotListReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScreenshotListReply.Marshal(b, m, deterministic)
}
func (dst *ScreenshotListReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScreenshotListReply.Merge(dst, src)
}
func (m *ScreenshotListReply) XXX_Size() int {
	return xxx_messageInfo_ScreenshotListReply.Size(m)
}
func (m *ScreenshotListReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ScreenshotListReply.DiscardUnknown(m)
}

var xxx_messageInfo_ScreenshotListReply proto.InternalMessageInfo

func (m *ScreenshotListReply) GetValue() []*Screenshot {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ScreenshotListReply) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ScreenshotListReply) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ScreenshotListReply) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func init() {
	proto.RegisterType((*Filter)(nil), "veidemann.api.Filter")
	proto.RegisterType((*CrawlLogListRequest)(nil), "veidemann.api.CrawlLogListRequest")
	proto.RegisterType((*CrawlLogListReply)(nil), "veidemann.api.CrawlLogListReply")
	proto.RegisterType((*PageLogListRequest)(nil), "veidemann.api.PageLogListRequest")
	proto.RegisterType((*PageLogListReply)(nil), "veidemann.api.PageLogListReply")
	proto.RegisterType((*ScreenshotListRequest)(nil), "veidemann.api.ScreenshotListRequest")
	proto.RegisterType((*ScreenshotListReply)(nil), "veidemann.api.ScreenshotListReply")
	proto.RegisterEnum("veidemann.api.Filter_Operator", Filter_Operator_name, Filter_Operator_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ReportClient is the client API for Report service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReportClient interface {
	// List crawl logs
	ListCrawlLogs(ctx context.Context, in *CrawlLogListRequest, opts ...grpc.CallOption) (*CrawlLogListReply, error)
	// List page logs
	ListPageLogs(ctx context.Context, in *PageLogListRequest, opts ...grpc.CallOption) (*PageLogListReply, error)
	// List screenshots
	ListScreenshots(ctx context.Context, in *ScreenshotListRequest, opts ...grpc.CallOption) (*ScreenshotListReply, error)
}

type reportClient struct {
	cc *grpc.ClientConn
}

func NewReportClient(cc *grpc.ClientConn) ReportClient {
	return &reportClient{cc}
}

func (c *reportClient) ListCrawlLogs(ctx context.Context, in *CrawlLogListRequest, opts ...grpc.CallOption) (*CrawlLogListReply, error) {
	out := new(CrawlLogListReply)
	err := c.cc.Invoke(ctx, "/veidemann.api.Report/ListCrawlLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportClient) ListPageLogs(ctx context.Context, in *PageLogListRequest, opts ...grpc.CallOption) (*PageLogListReply, error) {
	out := new(PageLogListReply)
	err := c.cc.Invoke(ctx, "/veidemann.api.Report/ListPageLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportClient) ListScreenshots(ctx context.Context, in *ScreenshotListRequest, opts ...grpc.CallOption) (*ScreenshotListReply, error) {
	out := new(ScreenshotListReply)
	err := c.cc.Invoke(ctx, "/veidemann.api.Report/ListScreenshots", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Report service

type ReportServer interface {
	// List crawl logs
	ListCrawlLogs(context.Context, *CrawlLogListRequest) (*CrawlLogListReply, error)
	// List page logs
	ListPageLogs(context.Context, *PageLogListRequest) (*PageLogListReply, error)
	// List screenshots
	ListScreenshots(context.Context, *ScreenshotListRequest) (*ScreenshotListReply, error)
}

func RegisterReportServer(s *grpc.Server, srv ReportServer) {
	s.RegisterService(&_Report_serviceDesc, srv)
}

func _Report_ListCrawlLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrawlLogListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServer).ListCrawlLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/veidemann.api.Report/ListCrawlLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServer).ListCrawlLogs(ctx, req.(*CrawlLogListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Report_ListPageLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageLogListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServer).ListPageLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/veidemann.api.Report/ListPageLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServer).ListPageLogs(ctx, req.(*PageLogListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Report_ListScreenshots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScreenshotListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServer).ListScreenshots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/veidemann.api.Report/ListScreenshots",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServer).ListScreenshots(ctx, req.(*ScreenshotListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Report_serviceDesc = grpc.ServiceDesc{
	ServiceName: "veidemann.api.Report",
	HandlerType: (*ReportServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListCrawlLogs",
			Handler:    _Report_ListCrawlLogs_Handler,
		},
		{
			MethodName: "ListPageLogs",
			Handler:    _Report_ListPageLogs_Handler,
		},
		{
			MethodName: "ListScreenshots",
			Handler:    _Report_ListScreenshots_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "report.proto",
}

func init() { proto.RegisterFile("report.proto", fileDescriptor_report_815df019fd9313b3) }

var fileDescriptor_report_815df019fd9313b3 = []byte{
	// 701 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x95, 0xcd, 0x52, 0x13, 0x4b,
	0x18, 0x86, 0x4f, 0x4f, 0x7e, 0x48, 0x3e, 0x20, 0xe4, 0x34, 0x3f, 0x19, 0x38, 0x70, 0x18, 0xa6,
	0xb4, 0x2a, 0x65, 0x91, 0x19, 0x2a, 0x96, 0x1b, 0x77, 0x80, 0x28, 0x54, 0x21, 0xc6, 0x81, 0x72,
	0xe1, 0x26, 0xd5, 0x24, 0xcd, 0xd0, 0x55, 0x33, 0xdd, 0xe3, 0x4c, 0x87, 0x08, 0xe5, 0xca, 0x8d,
	0xba, 0x70, 0xa3, 0xb7, 0xe0, 0x05, 0xe8, 0x45, 0x78, 0x05, 0xde, 0x82, 0x6b, 0xaf, 0xc1, 0xea,
	0x4e, 0x42, 0x7e, 0x04, 0x2c, 0xaa, 0x70, 0xe1, 0x6a, 0xa6, 0xbf, 0x7e, 0xa7, 0xdf, 0xf7, 0x7b,
	0xd2, 0xe9, 0x86, 0x89, 0x98, 0x46, 0x22, 0x96, 0x4e, 0x14, 0x0b, 0x29, 0xf0, 0xe4, 0x09, 0x65,
	0x4d, 0x1a, 0x12, 0xce, 0x1d, 0x12, 0xb1, 0x85, 0x42, 0x48, 0x93, 0x84, 0xf8, 0x34, 0xe9, 0x4c,
	0x2f, 0x2c, 0xfa, 0x42, 0xf8, 0x01, 0x75, 0x49, 0xc4, 0x5c, 0xc2, 0xb9, 0x90, 0x44, 0x32, 0xc1,
	0x7b, 0xb3, 0xab, 0xfa, 0xd1, 0xa8, 0xf8, 0x94, 0x57, 0x92, 0x36, 0xf1, 0x7d, 0x1a, 0xbb, 0x22,
	0xd2, 0x8a, 0x5f, 0xd5, 0xf6, 0x27, 0x04, 0xd9, 0x87, 0x2c, 0x90, 0x34, 0xc6, 0x4b, 0x00, 0x47,
	0x8c, 0x06, 0xcd, 0x3a, 0x27, 0x21, 0x35, 0x91, 0x85, 0xca, 0x79, 0x2f, 0xaf, 0x2b, 0x7b, 0x24,
	0xa4, 0xd8, 0x01, 0x43, 0x44, 0xa6, 0x61, 0xa1, 0x72, 0xa1, 0xfa, 0xbf, 0x33, 0x94, 0xd0, 0xe9,
	0xac, 0xe0, 0x3c, 0x89, 0x68, 0x4c, 0xa4, 0x88, 0x3d, 0x43, 0x44, 0x78, 0x06, 0x32, 0x27, 0x24,
	0x68, 0x51, 0x33, 0xa5, 0x57, 0xea, 0x0c, 0xec, 0x7b, 0x90, 0xeb, 0xa9, 0x70, 0x16, 0x8c, 0xad,
	0xa7, 0xc5, 0x7f, 0xd4, 0x73, 0x6f, 0xab, 0x88, 0x70, 0x1e, 0x32, 0x8f, 0xd7, 0x0f, 0x36, 0xb7,
	0x8b, 0x86, 0x2a, 0xed, 0x1e, 0x14, 0x53, 0xea, 0xf9, 0xe8, 0xa0, 0x98, 0xb6, 0xbf, 0x20, 0x98,
	0xde, 0x8c, 0x49, 0x3b, 0xd8, 0x15, 0xfe, 0x2e, 0x4b, 0xa4, 0x47, 0x5f, 0xb4, 0x68, 0x22, 0x71,
	0x09, 0xc6, 0xda, 0x24, 0x6e, 0xd4, 0x59, 0xd3, 0x44, 0x56, 0xaa, 0x9c, 0xf7, 0xb2, 0x6a, 0xb8,
	0xd3, 0xc4, 0x2b, 0x30, 0x41, 0x5f, 0xd2, 0x46, 0x4b, 0xf5, 0xaa, 0x66, 0x0d, 0x1d, 0x62, 0xfc,
	0xbc, 0xb6, 0xd3, 0xc4, 0x15, 0xc8, 0x1e, 0xe9, 0xdc, 0x66, 0xca, 0x4a, 0x95, 0xc7, 0xab, 0xb3,
	0x17, 0x36, 0xe5, 0x75, 0x45, 0xf8, 0x3f, 0xc8, 0x47, 0xc4, 0xa7, 0xf5, 0x84, 0x9d, 0x51, 0xb3,
	0x60, 0xa1, 0x72, 0xc6, 0xcb, 0xa9, 0xc2, 0x3e, 0x3b, 0xa3, 0x18, 0x43, 0x5a, 0xbd, 0x9b, 0x53,
	0xba, 0xae, 0xdf, 0xed, 0x77, 0x08, 0xfe, 0x1d, 0xce, 0x1c, 0x05, 0xa7, 0xb8, 0xd2, 0xc3, 0x82,
	0xb4, 0x69, 0x69, 0xc4, 0xb4, 0xf7, 0x41, 0x97, 0x97, 0xa2, 0xd8, 0x10, 0x2d, 0x2e, 0x75, 0x03,
	0x29, 0xaf, 0x33, 0xb8, 0x7e, 0x96, 0xcf, 0x08, 0x70, 0x8d, 0xf8, 0xf4, 0x2f, 0xc2, 0xf7, 0x06,
	0x41, 0x71, 0x28, 0xb2, 0xa2, 0xb7, 0x3a, 0x4c, 0x6f, 0x6e, 0xc4, 0xb3, 0xab, 0xbf, 0x61, 0x78,
	0x5f, 0x11, 0xcc, 0xee, 0x37, 0x62, 0x4a, 0x79, 0x72, 0x2c, 0xe4, 0x20, 0xbf, 0x02, 0x18, 0xe7,
	0xe8, 0x0c, 0xf6, 0x27, 0xb0, 0xcd, 0x43, 0x8e, 0x85, 0x7e, 0xbd, 0x49, 0x24, 0x31, 0xd3, 0x16,
	0x2a, 0xe7, 0xbc, 0x31, 0x16, 0xfa, 0x0f, 0x88, 0x24, 0xd7, 0xef, 0xe3, 0x3d, 0x82, 0xe9, 0xd1,
	0x3e, 0x14, 0x54, 0x77, 0x18, 0xea, 0xfc, 0x48, 0xa2, 0xfe, 0x27, 0x37, 0xcb, 0xb5, 0xfa, 0xc3,
	0x80, 0xac, 0xa7, 0xcf, 0x3d, 0x2c, 0x61, 0x52, 0xe5, 0xe9, 0xed, 0xfe, 0x04, 0xdb, 0x97, 0xfc,
	0x2f, 0x06, 0xe8, 0x2f, 0x58, 0x57, 0x6a, 0xa2, 0xe0, 0xd4, 0x5e, 0x7a, 0xfd, 0xed, 0xfb, 0x47,
	0xa3, 0x84, 0x67, 0xf5, 0x59, 0xd9, 0x39, 0x63, 0xdd, 0x86, 0x92, 0x05, 0xca, 0x24, 0x82, 0x09,
	0xa5, 0xed, 0xee, 0x9a, 0x04, 0xaf, 0x5c, 0xbc, 0x9d, 0x06, 0x3d, 0x97, 0xaf, 0x92, 0x28, 0xcb,
	0x45, 0x6d, 0x39, 0x87, 0x67, 0x06, 0x2d, 0x55, 0xbb, 0xda, 0xf1, 0x15, 0x4c, 0x29, 0x69, 0x1f,
	0x69, 0x82, 0x6f, 0x5d, 0x8a, 0x7b, 0xd0, 0xd7, 0xfe, 0x8d, 0x4a, 0x59, 0x2f, 0x6b, 0xeb, 0x79,
	0x5c, 0x1a, 0xb4, 0x4e, 0xfa, 0x56, 0x1b, 0x6f, 0xd1, 0x87, 0xf5, 0x1a, 0xde, 0x06, 0xf3, 0x59,
	0x6f, 0x2d, 0x6b, 0x53, 0x70, 0x19, 0x8b, 0x20, 0xa0, 0xb1, 0xb5, 0x5e, 0xdb, 0xb1, 0x6f, 0x43,
	0xfe, 0x7c, 0x0e, 0x9b, 0xc7, 0x52, 0x46, 0xc9, 0x7d, 0xd7, 0xf5, 0x99, 0x3c, 0x6e, 0x1d, 0x3a,
	0x0d, 0x11, 0xba, 0x3c, 0xe0, 0x6d, 0x52, 0xcd, 0xac, 0x39, 0x55, 0x67, 0xed, 0x4e, 0x1a, 0x19,
	0xa9, 0x34, 0x94, 0xb8, 0x70, 0xf8, 0xa1, 0xc3, 0x39, 0x19, 0xce, 0xb8, 0x31, 0xde, 0xf9, 0x71,
	0x6b, 0xea, 0xa2, 0x79, 0xde, 0xbf, 0xd3, 0xea, 0x24, 0x62, 0x87, 0x59, 0x7d, 0xfd, 0xdc, 0xfd,
	0x19, 0x00, 0x00, 0xff, 0xff, 0xc2, 0xf7, 0x69, 0x9a, 0xf9, 0x06, 0x00, 0x00,
}
